# Assignment 4
### CSC 478
#### Kristen Groom
#### 5/25/18

#### 1) PCA for Reduced Dimensionality in Clustering [Dataset: segmentation_data.zip]
For this problem you will use an image segmentation data set for clustering. You will experiment with using PCA as an approach to reduce dimensionality and noise in the data. You will compare the results of clustering the data with and without PCA using the provided image class assignments as the ground truth. The data set is divided into three files. The file "segmentation_data.txt" contains data about images with each line corresponding to one image. Each image is represented by 19 features (these are the columns in the data and correspond to the feature names in the file "segmentation_names.txt". The file "segmentation_classes.txt" contains the class labels (the type of image) and a numeric class label for each of the corresponding images in the data file. After clustering the image data, you will use the class labels to measure completeness and homogeneity of the generated clusters. The data set used in this problem is based on the Image Segmentation data set at the UCI Machine Learning Repository.



Your tasks in this problem are the following:

#### a) Load in the image data matrix (with rows as images and columns as features). Also load in the numeric class labels from the segmentation class file. Using your favorite method (e.g., sklearn's min-max scaler), perform min-max normalization on the data matrix so that each feature is scaled to [0,1] range.

In [6]:
# first import libraries to use in the assignment:
import numpy as np
import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 

In [7]:
# loading in the segmentation data
Data = pd.read_csv('segmentation_data/segmentation_data.txt', header=None, na_values=["?"])

In [8]:
Data.head(10)

0      1   2         3    4         5         6         7         8   \
0  110.0  189.0   9  0.000000  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.000000  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.000000  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.000000  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.000000  0.0  1.166667  0.691215  1.166667  1.005540   
5  157.0  221.0   9  0.000000  0.0  1.055556  0.646930  1.222222  0.620633   
6   62.0  224.0   9  0.000000  0.0  0.944445  1.083547  2.333333  1.632993   
7   27.0  248.0   9  0.111111  0.0  1.611111  0.646930  3.166667  1.722401   
8   44.0  233.0   9  0.000000  0.0  2.222222  2.146487  2.111111  1.327766   
9   17.0  229.0   9  0.000000  0.0  2.111111  1.985130  2.444445  1.614747   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   
5  12.111111  10.222222   8.111112  18.000000 -5.666666 -12.000000  17.666666   
6  14.629630  13.222222  11.444445  19.222221 -4.222222  -9.555555  13.777778   
7  15.296296  14.777778  12.888889  18.222221 -1.555556  -7.222222   8.777778   
8  14.481482  12.555555  11.333333  19.555555 -5.777778  -9.444445  15.222222   
9  13.703704  11.222222  11.111111  18.777779 -7.444445  -7.777778  15.222222   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654  
5  18.000000  0.549180  1.877146  
6  19.222221  0.408965  1.860191  
7  18.222221  0.312227  1.783512  
8  19.555555  0.422174  1.950405  
9  18.777779  0.439852  2.099904

In [9]:
Data.shape

(2100, 19)

In [10]:
# loading in the class labels
class_labels = pd.read_csv('segmentation_data/segmentation_classes.txt', sep='\t', header=None, index_col=0)

In [11]:
class_labels.head(10)

1
0       
GRASS  0
GRASS  0
GRASS  0
GRASS  0
GRASS  0
GRASS  0
GRASS  0
GRASS  0
GRASS  0
GRASS  0

In [12]:
class_labels.shape

(2100, 1)

In [13]:
# I want to get the class labels into a 1D array for computing Homogeneity and Completeness below:

In [14]:
target = np.asarray(class_labels[1])

In [15]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# we see that we have a data set with 2100 images and 19 features with a class data set of 2100 labels for the images

In [17]:
# checking for nan values:
nans_rows = Data[Data.isnull().any(axis=1)]

In [18]:
nans_rows

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Index: []

In [19]:
# I see that there are no nan values in our set

In [20]:
# normalization process using sklearn - scikit learn min-max scaler 
from sklearn import preprocessing

In [21]:
# we first create an instance of MinMaxScaler() to use to fit data
min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler.fit(Data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
# now transform the data using the min-max object
data_norm = min_max_scaler.fit_transform(Data)

In [23]:
# look at transformed data - output is 2D np.array
# viewing 10 images, and all columns
np.set_printoptions(precision=2, linewidth=100)
data_norm[:10,:]

array([[  4.31e-01,   7.42e-01,   0.00e+00,   0.00e+00,   0.00e+00,   3.42e-02,   6.72e-04,
          2.73e-02,   8.56e-04,   9.01e-02,   7.94e-02,   6.11e-02,   1.31e-01,   7.31e-01,
          1.41e-02,   8.73e-01,   1.24e-01,   5.08e-01,   8.32e-01],
       [  3.36e-01,   7.33e-01,   0.00e+00,   0.00e+00,   0.00e+00,   3.80e-02,   7.26e-04,
          3.23e-02,   5.41e-04,   9.58e-02,   8.51e-02,   6.85e-02,   1.35e-01,   7.29e-01,
          2.35e-02,   8.60e-01,   1.27e-01,   4.63e-01,   8.37e-01],
       [  8.85e-01,   9.71e-01,   0.00e+00,   0.00e+00,   0.00e+00,   1.16e-01,   2.21e-03,
          6.71e-02,   1.10e-03,   8.55e-02,   7.54e-02,   6.19e-02,   1.20e-01,   7.37e-01,
          3.88e-02,   8.27e-01,   1.13e-01,   4.80e-01,   8.45e-01],
       [  1.82e-01,   9.21e-01,   0.00e+00,   0.00e+00,   0.00e+00,   4.37e-02,   1.27e-03,
          2.24e-02,   6.45e-04,   8.86e-02,   8.02e-02,   5.96e-02,   1.27e-01,   7.48e-01,
          1.41e-02,   8.56e-01,   1.20e-01,   5.01e-01,  

#### b) Next, Perform Kmeans clustering (for this problem, use the Kmeans implementation in scikit-learn) on the image data (since there are a total 7 pre-assigned image classes, you should use K = 7 in your clustering). Use Euclidean distance as your distance measure for the clustering. Print the cluster centroids (use some formatting so that they are visually understandable). Compare your 7 clusters to the 7 pre-assigned classes by computing the Completeness and Homogeneity values of the generated clusters.

In [24]:
# using KMeans from scikit-learn
# the following is the initialization using 7 clusters
# KMeans algorithm in scikit-learn uses Euclidean distance as default
# so we do not need to do anything to that argument
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) 

In [25]:
# now fit the model
kmeans.fit(data_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 389.396864395
start iteration
done sorting
end inner loop
Iteration 1, inertia 373.156515474
start iteration
done sorting
end inner loop
Iteration 2, inertia 367.28018715
start iteration
done sorting
end inner loop
Iteration 3, inertia 365.86228747
start iteration
done sorting
end inner loop
Iteration 4, inertia 365.691767533
start iteration
done sorting
end inner loop
Iteration 5, inertia 365.612182302
start iteration
done sorting
end inner loop
Iteration 6, inertia 365.536540537
start iteration
done sorting
end inner loop
Iteration 7, inertia 365.256996145
start iteration
done sorting
end inner loop
Iteration 8, inertia 364.312202492
start iteration
done sorting
end inner loop
Iteration 9, inertia 363.001476238
start iteration
done sorting
end inner loop
Iteration 10, inertia 361.854213216
start iteration
done sorting
end inner loop
Iteration 11, inertia 360.001704013
start iteration
done sorting

end inner loop
Iteration 17, inertia 379.010897575
start iteration
done sorting
end inner loop
Iteration 18, inertia 379.010897575
center shift 0.000000e+00 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 374.507437802
start iteration
done sorting
end inner loop
Iteration 1, inertia 364.712407081
start iteration
done sorting
end inner loop
Iteration 2, inertia 362.154701358
start iteration
done sorting
end inner loop
Iteration 3, inertia 360.783974513
start iteration
done sorting
end inner loop
Iteration 4, inertia 358.807170159
start iteration
done sorting
end inner loop
Iteration 5, inertia 355.87975962
start iteration
done sorting
end inner loop
Iteration 6, inertia 353.512786769
start iteration
done sorting
end inner loop
Iteration 7, inertia 351.86029569
start iteration
done sorting
end inner loop
Iteration 8, inertia 351.480869326
start iteration
done sorting
end inner loop
Iteration 9, inertia 351.282311127
s

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [26]:
# now using .predict() - find our clusters:
clusters = kmeans.predict(data_norm)

In [27]:
# looking at our clusters:
clusters[:200]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 4, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5,
       5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5,
       4, 5, 4, 5, 5, 5, 4, 4, 4, 5, 4, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], dtype=int32)

In [28]:
# we can also look at the centroids using scikit-learn cluster_centers_
centroids = kmeans.cluster_centers_

In [29]:
print centroids

[[  2.54e-01   4.60e-01   0.00e+00   2.63e-02   1.37e-02   3.73e-02   2.37e-03   2.79e-02   2.02e-03
    2.59e-02   1.78e-02   4.23e-02   1.65e-02   7.69e-01   2.16e-01   5.08e-01   4.33e-02   8.03e-01
    1.81e-01]
 [  5.35e-01   1.50e-01   0.00e+00   2.78e-02   1.67e-03   3.02e-02   5.43e-04   2.68e-02   5.87e-04
    8.23e-01   7.80e-01   8.94e-01   7.89e-01   2.71e-01   6.66e-01   2.89e-01   8.94e-01   2.12e-01
    1.25e-01]
 [  2.56e-01   3.93e-01   0.00e+00   7.45e-02   1.91e-02   7.73e-02   4.10e-03   6.06e-02   4.97e-03
    1.48e-01   1.38e-01   1.85e-01   1.19e-01   7.17e-01   3.44e-01   3.55e-01   1.85e-01   4.12e-01
    2.02e-01]
 [  5.14e-01   8.09e-01   0.00e+00   7.74e-02   5.05e-03   5.45e-02   1.41e-03   4.63e-02   1.40e-03
    1.09e-01   9.14e-02   9.24e-02   1.43e-01   6.79e-01   7.90e-02   8.21e-01   1.35e-01   4.14e-01
    8.92e-01]
 [  3.03e-01   5.31e-01   0.00e+00   5.23e-02   4.66e-02   1.01e-01   9.42e-03   8.40e-02   1.10e-02
    4.01e-01   3.70e-01   4.72e-01 

In [30]:
# need to read in the features names:
# These refer to the columns in our data matrix

features = np.genfromtxt('segmentation_data/segmentation_names.txt',dtype='str')

In [31]:
features

array(['REGION-CENTROID-COL', 'REGION-CENTROID-ROW', 'REGION-PIXEL-COUNT', 'SHORT-LINE-DENSITY-5',
       'SHORT-LINE-DENSITY-2', 'VEDGE-MEAN', 'VEDGE-SD', 'HEDGE-MEAN', 'HEDGE-SD', 'INTENSITY-MEAN',
       'RAWRED-MEAN', 'RAWBLUE-MEAN', 'RAWGREEN-MEAN', 'EXRED-MEAN', 'EXBLUE-MEAN', 'EXGREEN-MEAN',
       'VALUE-MEAN', 'SATURATION-MEAN', 'HUE-MEAN'], 
      dtype='|S20')

In [32]:
# Format centroids so they give us more information:
# looking at the centroids
print "\t\t\tCluster0   Cluster1  Cluster2   Cluster3   Cluster4   Cluster5   Cluster6"
for i in range(10):
    print "{:<25}{:<10.4f}{:<7.4f}{:>10.4f}\t{:.4f}\t{:>10.4f}\t{:<7.4f}\t{:>8.4f}".format(features[i],centroids[0][i],
                                     centroids[1][i],
                                     centroids[2][i],centroids[3][i],centroids[4][i],
                                     centroids[5][i],centroids[6][i])


			Cluster0   Cluster1  Cluster2   Cluster3   Cluster4   Cluster5   Cluster6
REGION-CENTROID-COL      0.2536    0.5351     0.2561	0.5140	    0.3025	0.7513 	  0.7689
REGION-CENTROID-ROW      0.4599    0.1502     0.3935	0.8089	    0.5309	0.5341 	  0.4255
REGION-PIXEL-COUNT       0.0000    0.0000     0.0000	0.0000	    0.0000	0.0000 	  0.0000
SHORT-LINE-DENSITY-5     0.0263    0.0278     0.0745	0.0774	    0.0523	0.0399 	  0.0140
SHORT-LINE-DENSITY-2     0.0137    0.0017     0.0191	0.0051	    0.0466	0.0383 	  0.0226
VEDGE-MEAN               0.0373    0.0302     0.0773	0.0545	    0.1008	0.1147 	  0.0396
VEDGE-SD                 0.0024    0.0005     0.0041	0.0014	    0.0094	0.0193 	  0.0030
HEDGE-MEAN               0.0279    0.0268     0.0606	0.0463	    0.0840	0.1090 	  0.0231
HEDGE-SD                 0.0020    0.0006     0.0050	0.0014	    0.0110	0.0179 	  0.0021
INTENSITY-MEAN           0.0259    0.8232     0.1482	0.1088	    0.4006	0.3005 	  0.0408


In [33]:
# Comparing clusters with target values using Homogeneity and Completeness

In [34]:
# Homogeneity: each cluster contains only members of a single class. 
# Completeness: all members of a given class are assigned to the same cluster.
from sklearn.metrics import completeness_score, homogeneity_score

In [35]:
print completeness_score(target,clusters)

0.612634628644


In [36]:
print homogeneity_score(target,clusters)

0.610934710766


#### c) Perform PCA on the normalized image data matrix. You may use the linear algebra package in Numpy or the Decomposition module in scikit-learn (the latter is much more efficient). Analyze the principal components to determine the number, r, of PCs needed to capture at least 95% of variance in the data. Then use these r components as features to transform the data into a reduced dimension space. [See the PCA Clustering Notebook from class for an example of how these steps are performed.]

In [37]:
# import sklearn library for PCA process
from sklearn import decomposition

In [38]:
# I'll start with 5 principle components to see if we capture >=95% of variance in the data
pca = decomposition.PCA(n_components=5)
data_trans = pca.fit(data_norm).transform(data_norm)

In [39]:
# looking at our transformed data
np.set_printoptions(precision=2,suppress=True)
print data_trans

[[-0.69  0.53  0.25 -0.2  -0.08]
 [-0.67  0.51  0.34 -0.17 -0.04]
 [-0.71  0.77 -0.16 -0.01 -0.17]
 ..., 
 [-0.51 -0.13 -0.08  0.1  -0.03]
 [-0.48 -0.09 -0.16  0.11  0.  ]
 [-0.44 -0.11 -0.05  0.15  0.02]]


In [40]:
# and now we can look at the ratios for top 5 principle components
print(pca.explained_variance_ratio_)

[ 0.61  0.13  0.1   0.05  0.04]


In [41]:
sum(pca.explained_variance_ratio_)

0.9212588648109572

In [42]:
# not quite at 95% so we can try again with 6 and 7:
for i in range(6,9):
    pca = decomposition.PCA(n_components=i)
    data_trans = pca.fit(data_norm).transform(data_norm)
    print(sum(pca.explained_variance_ratio_))

0.941139219796
0.96005892277
0.976213010819


In [43]:
# ok, I see that 7 principle components capture >95% of the variance in the data
# so redoing our transformation at r=6
pca = decomposition.PCA(n_components=6)
data_trans = pca.fit(data_norm).transform(data_norm)

#### d) Perform Kmeans again, but this time on the lower dimensional transformed data. Then, compute the Completeness and Homogeneity values of the new clusters.

In [44]:
# performing Kmeans again using transformed data
kmeans.fit(data_trans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 285.515162752
start iteration
done sorting
end inner loop
Iteration 1, inertia 273.682398754
start iteration
done sorting
end inner loop
Iteration 2, inertia 273.247717971
start iteration
done sorting
end inner loop
Iteration 3, inertia 273.15084109
start iteration
done sorting
end inner loop
Iteration 4, inertia 273.101348465
start iteration
done sorting
end inner loop
Iteration 5, inertia 273.073454665
start iteration
done sorting
end inner loop
Iteration 6, inertia 273.073454665
center shift 0.000000e+00 within tolerance 1.236861e-05
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 310.273593438
start iteration
done sorting
end inner loop
Iteration 1, inertia 289.666824299
start iteration
done sorting
end inner loop
Iteration 2, inertia 285.685681674
start iteration
done sorting
end inner loop
Iteration 3, inertia 284.003586763
start iteration
done sorting

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [45]:
# getting our clusters
clusters = kmeans.predict(data_trans)

In [46]:
# viewing Completeness and Homogeneity
print "Completeness Score: {}".format(completeness_score(target,clusters))
print "Homogeneity Score: {}".format(homogeneity_score(target,clusters))

Completeness Score: 0.612709095526
Homogeneity Score: 0.61104199707


#### e) Discuss your observations based on the comparison of the two clustering results.

I see that scores dropped slightly for both Completeness and Homogeneity.
This could mean that the data may have a lot of noise in the original data, however, the scores are not much lower and we know that PCA can increase computational efficiency so even though it did not increase accuracy, it can still be a useful process in making data more usable for further machine learning tasks.

#### 2) Item-Based Joke Recommendation [Dataset: jokes.zip]

For this problem you will use a modified version of the item-based recommender algorithm from Ch. 14 of Machine Learning in Action and use it on joke ratings data based on Jester Online Joke Recommender System. The modified version of the code is provided in the module itemBasedRec.py. Most of the module will be used as is, but you will add some additional functionality.

The data set contains two files. The file "modified_jester_data.csv" contains the ratings on 100 jokes by 1000 users (each row is a user profile). The ratings have been normalized to be between 1 and 21 (a 20-point scale), with 1 being the lowest rating. A zero indicated a missing rating. The file "jokes.csv" contains the joke ids mapped to the actual text of the jokes.

Your tasks in this problem are the following (please also see comments for the function stubs in the provided module):

#### a) Load in the joke ratings data and the joke text data into appropriate data structures.

In [64]:
joke_data = pd.read_csv('jokes/modified_jester_data.csv', header=None, na_values=["?"])

In [65]:
joke_data.head(10)

0      1      2      3      4      5      6      7      8      9   \
0   3.18  19.79   1.34   2.84   3.48   2.50   1.15  15.17   2.02   6.24   
1  15.08  10.71  17.36  15.37   8.62   1.34  10.27   5.66  19.88  20.22   
2   0.00   0.00   0.00   0.00  20.03  20.27  20.03  20.27   0.00   0.00   
3   0.00  19.35   0.00   0.00  12.80  19.16   8.18  17.21   0.00  12.84   
4  19.50  15.61   6.83   5.61  12.36  12.60  18.04  15.61  10.56  16.73   
5   4.83   7.46  11.44   2.50   3.91   6.68   2.31  10.13   4.35   9.20   
6   0.00   0.00   0.00   0.00  19.59   1.15  18.72  19.79   0.00   0.00   
7  17.84  14.16  20.17   4.79   2.84   9.30  20.27  12.41   5.81   6.58   
8   7.21   7.46   1.58   4.11   2.26  10.71   5.71   2.07   3.14   9.40   
9  14.01  16.15  16.15  14.01  17.41  16.15  19.93  13.52  14.01  19.16   

   ...       90     91     92     93     94     95     96     97     98     99  
0  ...    13.82   0.00   0.00   0.00   0.00   0.00   5.37   0.00   0.00   0.00  
1  ...    13.82   6.05  10.71  18.86  10.81   8.86  14.06  11.34   6.68  12.07  
2  ...     0.00   0.00   0.00  20.08   0.00   0.00   0.00   0.00   0.00   0.00  
3  ...     0.00   0.00   0.00  11.53   0.00   0.00   0.00   0.00   0.00   0.00  
4  ...    16.19  16.58  15.27  16.19  16.73  12.55  14.11  17.55  12.80  12.60  
5  ...     7.46   4.11  10.32   8.04   8.82   7.65  11.05   1.92   5.95   7.55  
6  ...     0.00   0.00   0.00   0.00   0.00  13.33   0.00   0.00   0.00   0.00  
7  ...    18.23   9.88  10.90   5.32   7.84   7.65  13.14  10.95  12.31  11.00  
8  ...    15.37  10.71  15.17  10.71  10.71  10.71  10.71  10.71   7.60   6.05  
9  ...     0.00  15.47   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00  

[10 rows x 100 columns]

In [66]:
jokes = np.genfromtxt('jokes/jokes.csv', delimiter=',', dtype=str)
jokes = np.array(jokes[:,1])

In [67]:
jokes.shape

(100,)

In [52]:
jokes[:10]

array([ 'A man visits the doctor. The doctor says "I have bad news for you.You have cancer and Alzheimer\'s disease". The man replies "Well thank God I don\'t have cancer!"',
       'This couple had an excellent relationship going until one day he came home from work to find his girlfriend packing. He asked her why she was leaving him and she told him that she had heard awful things about him. "What could they possibly have said to make you move out?" "They told me that you were a pedophile." He replied "That\'s an awfully big word for a ten year old."',
       "Q. What's 200 feet long and has 4 teeth? A. The front row at a Willie Nelson Concert.",
       "Q. What's the difference between a man and a toilet? A. A toilet doesn't follow you around after you use it.",
       "Q. What's O. J. Simpson's Internet address? A.\tSlash slash backslash slash slash escape.",
       "Bill & Hillary are on a trip back to Arkansas. They're almost out of gas so Bill pulls into a service station on the

In [53]:
# checking out a joke:
jokes[4]

"Q. What's O. J. Simpson's Internet address? A.\tSlash slash backslash slash slash escape."

#### b) Complete the definition for the function "test". This function iterates over all users and for each performs evaluation (by calling the provided "cross_validate_user" function), and returns the error information necessary to compute Mean Absolute Error (MAE). Use this function to perform evaluation (wiht 20% test-ratio for each user) comparing MAE results using standard item-based collaborative filtering (based on the rating prediction function "standEst") with results using the SVD-based version of the rating item-based CF (using "svdEst" as the prediction engine). [Note: See comments provided in the module for hints on accomplishing these tasks.]

In [54]:
# I decided to run the functions here so I can test my code in sections more easily...

In [55]:
from numpy import *
from numpy import linalg as la
import numpy as np

def ecludSim(inA,inB):
    return 1.0 / (1.0 + la.norm(inA - inB))

def pearsSim(inA,inB):
    if len(inA) < 3 : return 1.0
    return 0.5 + 0.5 * corrcoef(inA, inB, rowvar = 0)[0][1]

def cosSim(inA,inB):
    num = float(inA.T * inB)
    denom = la.norm(inA)*la.norm(inB)
    return 0.5 + 0.5 * (num / denom)

In [56]:
def standEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0: continue
        overLap = nonzero(logical_and(dataMat[:,item]>0, \
                                      dataMat[:,j]>0))[0]
        if len(overLap) == 0: similarity = 0
        else: similarity = simMeas(dataMat[overLap,item], \
                                   dataMat[overLap,j])
        #print 'the %d and %d similarity is: %f' % (item, j, similarity)
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

In [57]:
def svdEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    data=mat(dataMat)
    U,Sigma,VT = la.svd(data)
    Sig4 = mat(eye(4)*Sigma[:4]) #arrange Sig4 into a diagonal matrix
    xformedItems = data.T * U[:,:4] * Sig4.I  #create transformed items
    for j in range(n):
        userRating = data[user,j]
        if userRating == 0 or j==item: continue
        similarity = simMeas(xformedItems[item,:].T,\
                             xformedItems[j,:].T)
        #print 'the %d and %d similarity is: %f' % (item, j, similarity)
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

In [58]:
# This function is not needed for Assignment 4, but may be useful for experimentation
def recommend(dataMat, user, N=3, simMeas=cosSim, estMethod=standEst):
    unratedItems = nonzero(dataMat[user,:].A==0)[1] #find unrated items 
    if len(unratedItems) == 0: return 'you rated everything'
    itemScores = []
    for item in unratedItems:
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        itemScores.append((item, estimatedScore))
    return sorted(itemScores, key=lambda jj: jj[1], reverse=True)[:N]

# This function performs evaluation on a single user based on the test_ratio
# For example, with test_ratio = 0.2, a randomly selected 20 percent of rated 
# items by the user are withheld and the rest are used to estimate the withheld ratings

In [59]:
def cross_validate_user(dataMat, user, test_ratio, estMethod=standEst, simMeas=pearsSim):
    number_of_items = np.shape(dataMat)[1]
    rated_items_by_user = np.array([i for i in range(number_of_items) if dataMat[user,i]>0])
    test_size = test_ratio * len(rated_items_by_user)
    # getting an error here - needs to return an int not a float...
    # so I'll use floor to get it to work:
    test_size = int(floor(test_size))
    test_indices = np.random.randint(0, len(rated_items_by_user), test_size)

    withheld_items = rated_items_by_user[test_indices]
    original_user_profile = np.copy(dataMat[user])
    dataMat[user, withheld_items] = 0 # So that the withheld test item is not used in the rating estimation below
    error_u = 0.0
    count_u = len(withheld_items)

    # Compute absolute error for user u over all test items
    for item in withheld_items:
        # Estimate rating on the withheld item
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        error_u = error_u + abs(estimatedScore - original_user_profile[item])	

    # Now restore ratings of the withheld items to the user profile
    for item in withheld_items:
        dataMat[user, item] = original_user_profile[item]

    # Return sum of absolute errors and the count of test cases for this user
    # Note that these will have to be accumulated for each user to compute MAE
    return error_u, count_u

In [60]:
def test(dataMat, test_ratio, estMethod):
    
    # read the directions above on how I'm supposed to do this...
    
    # Write this function to iterate over all users and for each perform evaluation by calling
    # the above cross_validate_user function on each user. MAE will be the ratio of total error 
    # across all test cases to the total number of test cases, for all users
    
    # call cross_validate_user on each user to find total MAE
    total_error = 0
    total_count = 0
    for i in range(len(dataMat)):
        error_u, count_u = cross_validate_user(dataMat, i, test_ratio, estMethod=standEst, simMeas=pearsSim)
        total_error += error_u
        total_count += count_u
    MAE = total_error/len(dataMat)
    print('Mean Absoloute Error for {} : {}'.format(estMethod, MAE))

In [61]:
dataMat = genfromtxt('jokes/modified_jester_data.csv',delimiter=',')

In [62]:
dataMat

array([[  3.18,  19.79,   1.34, ...,   0.  ,   0.  ,   0.  ],
       [ 15.08,  10.71,  17.36, ...,  11.34,   6.68,  12.07],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       ..., 
       [ 16.58,  16.63,  15.85, ...,   0.  ,   0.  ,   0.  ],
       [  3.67,   4.45,   3.67, ...,   3.77,   3.77,   3.28],
       [  9.88,  11.73,   9.16, ...,   0.  ,   0.  ,   0.  ]])

In [96]:
# we can transpose to have rows be the jokes and columns as user ratings
dataMat_t = dataMat.T

In [97]:
dataMat_t

array([[  3.18,  15.08,   0.  , ...,  16.58,   3.67,   9.88],
       [ 19.79,  10.71,   0.  , ...,  16.63,   4.45,  11.73],
       [  1.34,  17.36,   0.  , ...,  15.85,   3.67,   9.16],
       ..., 
       [  0.  ,  11.34,   0.  , ...,   0.  ,   3.77,   0.  ],
       [  0.  ,   6.68,   0.  , ...,   0.  ,   3.77,   0.  ],
       [  0.  ,  12.07,   0.  , ...,   0.  ,   3.28,   0.  ]])

In [98]:
# I can see that each row is now representing an individual joke with ratings
dataMat_t[0]

array([  3.18,  15.08,   0.  ,   0.  ,  19.5 ,   4.83,   0.  ,  17.84,   7.21,  14.01,   8.09,
        12.31,   0.  ,  20.22,  19.79,   7.5 ,   0.  ,  14.16,  15.22,   0.  ,  13.57,  18.28,
        13.72,  13.09,   7.07,   0.  ,   0.  ,  11.49,   0.  ,   0.  ,  12.94,   0.  ,  12.02,
         0.  ,  16.92,   1.34,  18.18,   7.31,  13.96,   0.  ,   6.05,   0.  ,   0.  ,  11.15,
        19.79,  18.33,  19.45,   2.75,   5.56,   3.18,  14.16,   0.  ,   0.  ,   2.41,  19.11,
         8.72,  17.21,  17.94,   3.57,   0.  ,  15.56,  12.26,  11.29,  12.26,  10.71,   0.  ,
         9.4 ,  14.4 ,   3.96,   0.  ,  14.5 ,   4.79,  16.44,  20.27,  13.38,   0.  ,   2.5 ,
         0.  ,  13.28,   0.  ,   0.  ,  14.45,  14.06,   3.33,   0.  ,   9.5 ,  13.82,  17.89,
         4.93,  10.08,   7.84,   0.  ,   0.  ,   9.74,  19.16,  11.44,  14.54,   0.  ,  14.3 ,
         0.  ,   0.  ,  17.17,  16.68,   9.11,  10.08,   0.  ,  14.45,   8.82,  16.39,  14.11,
        14.06,   0.  ,  13.38,   0.  ,  15.61,   6

In [99]:
# import pdb

# test_ratio = 0.2
# number_of_items = np.shape(dataMat)[1]
# rated_items_by_user = np.array([i for i in range(number_of_items) if dataMat[0,i]>0])
# test_size = test_ratio * len(rated_items_by_user)
# # pdb.set_trace()

# test_size = int(floor(test_size))
# print(test_size)
# # getting an error here - needs to return an int not a float...
# test_indices = np.random.randint(0, len(rated_items_by_user), test_size)

In [63]:
dataMat.shape

(1000, 100)

In [74]:
test(dataMat, 0.2, svdEst)
test(dataMat, 0.2, standEst)

('Mean Absoloute Error for ', <function svdEst at 0x1115737d0>, ' : ', 50.811411444792242)
('Mean Absoloute Error for ', <function standEst at 0x111573500>, ' : ', 50.703675043164594)


#### c) Write a new function "print_most_similar_jokes" which takes the joke ratings data, a query joke id, a parameter k for the number of nearest neighbors, and a similarity metric function, and prints the text of the query joke as well as the texts of the top k most similar jokes based on user ratings. [Note: For hints on how to accomplish this task, please see comments at the end of the provided module as well as comments for the provided stub function.]

In [100]:
def print_most_similar_jokes(dataMat, jokes, queryJoke, k, metric=pearsSim):
    # Write this function to find the k most similar jokes (based on user ratings) to a queryJoke
    # The queryJoke is a joke id as given in the 'jokes.csv' file (an corresponding to the a column in dataMat)
    # You must compare ratings for the queryJoke (the column in dataMat corresponding to the joke), to all
    # other joke rating vectors and return the top k. Note that this is the same as performing KNN on the 
    # columns of dataMat. The function must retrieve the text of the joke from 'jokes.csv' file and print both
    # the queryJoke text as well as the text of the returned jokes.
    
    # compare each column in the data matrix - or each row in the    
    # for each row(user) i - find the similarity between dataMat_t[i] and dataMat_t[queryJoke]
    sims = np.array([metric(dataMat[queryJoke],dataMat[i]) for i in range(len(dataMat))])
    
    # using knn algorithm from class - we can use distances then sort in increasing order
    distances = 1 - sims
    idx = np.argsort(distances) 
    top_k_jokes = idx[1:k+1]
    
    print("Selected Joke: \nJoke #{}: {}\n".format(queryJoke, jokes[queryJoke]))
    print('Top {} recommended jokes: \n'.format(k))
    for i in top_k_jokes:
        print('Joke #{}: {}'.format(i,jokes[i]))
        print('--'*20)


In [101]:
# We already loaded jokes in above
print_most_similar_jokes(dataMat_t, jokes, 3, 5, pearsSim)

Selected Joke: 
Joke #3: Q. What's the difference between a man and a toilet? A. A toilet doesn't follow you around after you use it.

Top 5 recommended jokes: 

Joke #23: What do you get when you run over a parakeet with a lawnmower? Shredded tweet.
----------------------------------------
Joke #8: A country guy goes into a city bar that has a dress code and the maitred' demands he wear a tie. Discouraged the guy goes to his car to sulk when inspiration strikes: He's got jumper cables in the trunk! So he wraps them around his neck sort of like a string tie (a bulky string tie to be sure) and returns to the bar. The maitre d' is reluctant but says to the guy "Okay you're a pretty resourceful fellow you can come in... but just don't start anything"!
----------------------------------------
Joke #2: Q. What's 200 feet long and has 4 teeth? A. The front row at a Willie Nelson Concert.
----------------------------------------
Joke #32: What do you call an American in the finals of the worl